//
// Created by james on 7/16/2026.
//

#ifndef PATHFINDERMINIEXTREME_025_MONSTERSPRITES_H
#define PATHFINDERMINIEXTREME_025_MONSTERSPRITES_H


class monstersprites {
};


#endif //PATHFINDERMINIEXTREME_025_MONSTERSPRITES_H
